server:
  port: 3993
eureka:
  instance:
    instance-id: ${spring.application.name}(${spring.cloud.client.ip-address}:${server.port})
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:Hande2021@localhost:10907/eureka
spring:
  application:
    name: microserver-otherserver
  #  profiles:
  #    active: dev
  # 设置时区和json统一时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  #redis单机版
  redis:
    host: 106.15.177.69
    port: 43999
    password: Hande@.7b61a2
    timeout: 60000
    database: 15
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8

#日志
#logging:
#  level:
#    root: info
#  file:
#    name: security.log
#    path: /home/local/web_service/security
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印日志
#  type-aliases-package: com.hande.management.model
#  mapper-locations: classpath*:/mapper/*.xml
#  global-config:
#    db-config:
#      logic-delete-field: delEnable  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper:
#  helper-dialect: mysql
#
#phospherus:
#  security:
#    token:
#      alias: phospherus
#      jwt-file-name: jwt.jks
#      jwt-password: phospherus
#    login:
#      /auth/login
#    # 白名单列表 无需验证登录
#    ignored:
#      - /rsa/publicKey # 获取公钥
#      - /oauth/token
#      - /oauth/check_token
#      - /user/login
#      - /login
#      - /health
#      - /api/socket/**
#    # 需要验证，但是不需要具体角色,登录即可访问
#    not-role:
#      - /user