server:
  port: 39393

spring:
  application:
    name: csrf-test
  security:
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iron-door?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456